spring:
  application:
    name: zipkin-testing
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
server:
  shutdown: graceful
monitoring:
  prometheus-password: password
